---

# Set these if you are forwarding zones (you probably are not)
idm_dns_forward_zones:
  - name: "home"
    forwarders:
      - ip_address: "192.168.100.2"
      - ip_address: "192.168.1.1"
    forward_policy: "only"
    skip_overlap_check: true

# Set the bind policy for zones managed by the IdM server
# The realm-capsule bind policy should be much more restrictive
idm_dns_update_zones:
  - name: "demo.net"
    foreman_proxy_BIND_update_policy: 'grant DEMO.NET krb5-self * A; grant DEMO.NET krb5-self * AAAA; grant DEMO.NET krb5-self * SSHFP; grant realm-capsule\@DEMO.NET wildcard * ANY;' # noqa yaml[line-length]
  - name: "168.192.in-addr.arpa"
    foreman_proxy_BIND_update_policy: 'grant DEMO.NET krb5-subdomain 168.192.in-addr.arpa. PTR; grant realm-capsule\@DEMO.NET wildcard * ANY;'
  - name: "25.168.192.in-addr.arpa"
    foreman_proxy_BIND_update_policy: 'grant DEMO.NET krb5-subdomain 254.168.192.in-addr.arpa. PTR; grant realm-capsule\@DEMO.NET wildcard * ANY;'

idm_dns_records:
  - name: "nas3"
    zone_name: "demo.net"
    record_type: "A"
    ip_address: "192.168.25.3"
    a_create_reverse: true
    state: "present"

  - name: "switch"
    zone_name: "demo.net"
    record_type: "A"
    ip_address: "192.168.25.2"
    state: "present"

  - name: "vcenter"
    zone_name: "demo.net"
    record_type: "A"
    ip_address: "192.168.25.30"
    a_create_reverse: true
    state: "present"

  - name: "c3esx1"
    zone_name: "demo.net"
    record_type: "A"
    ip_address: "192.168.25.31"
    a_create_reverse: true
    state: "present"

  - name: "c3esx2"
    zone_name: "demo.net"
    record_type: "A"
    ip_address: "192.168.25.32"
    a_create_reverse: true
    state: "present"

  - name: "c3esx3"
    zone_name: "demo.net"
    record_type: "A"
    ip_address: "192.168.25.33"
    a_create_reverse: true
    state: "present"

  - name: "c3esx4"
    zone_name: "demo.net"
    record_type: "A"
    ip_address: "192.168.25.34"
    a_create_reverse: true
    state: "present"

  - name: "c3esx5"
  - name: "switch"
    zone_name: "demo.net"
    record_type: "A"
    ip_address: "192.168.25.35"
    a_create_reverse: true
    state: "present"

  - name: "c3esx6"
    zone_name: "demo.net"
    record_type: "A"
    ip_address: "192.168.25.36"
    a_create_reverse: true
    state: "present"

  - name: "c3esx7"
    zone_name: "demo.net"
    record_type: "A"
    ip_address: "192.168.25.37"
    a_create_reverse: true
    state: "present"
